apiVersion: apps/v1
kind: Deployment
metadata:
  name: polar-mysql-catalog
  labels:
    app: polar-mysql-catalog
spec:
  selector:
    matchLabels:
      app: polar-mysql-catalog
  template:
    metadata:
      labels:
        app: polar-mysql-catalog
    spec:
      containers:
      - name: polar-mysql-catalog
        image: mysql:8.0
        command: [ "sleep" ]
        args: [ "infinity" ]
        env:
          - name: MYSQL_DATABASE
            value: polardb_catalog
          - name: MYSQL_USER
            value: user
          - name: MYSQL_PASSWORD
            value: password
          - name: MYSQL_ROOT_PASSWORD
            value: password   
        ports:
          - containerPort: 3306                             
        resources:
          requests:
            cpu: 100m
            memory: 60Mi
          limits:
            cpu: 200m
            memory: 120Mi

---

apiVersion: v1
kind: Service
metadata:
  name: polar-mysql-catalog
  labels:
    app: polar-mysql-catalog
spec:
  type: ExternalName
  externalName: host.docker.internal
  selector:
    app: polar-mysql-catalog
  ports:
  - protocol: TCP
    port: 3306
    targetPort: 3306

